server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 500

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379

ignoa:
  cloudfront-origin:
    enabled: ${CLOUDFRONT_ORIGIN_VERIFICATION_ENABLED}
    secret: ${CLOUDFRONT_ORIGIN_VERIFY_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ignoa-api
    distribution:
      percentiles-histogram:
        http.server.requests: true
        lock.hold.time: true
        lock.acquire.wait: true
        hikaricp.connections.acquire: true
